[package]
name = "relag"
version = "0.0.4"
edition = "2024"

[features]
monitor = []

[dependencies]
clap = { version = "4", features = ["derive"] }
dashmap = { version = "6", features = ["rayon"] }
fixedbitset = "0.5.7"
indicatif = "0.17"
quick_cache = "0.6"
mimalloc = { version = "0.1", default-features = false }
parking_lot = "0.12"
parasail-rs = "0.9.0"
rand = "0.10.0"
rayon = "1.10"
rustc-hash = "2.1.2"
smallvec = "1.15"
rich_rust = "0.2.1"
regex = "1.12.3"
clap_complete = "4.6.2"
petgraph = "0.8.3"
bincode = { version = "<3.0", features = ["derive"] }
ndarray = "0.17.2"
molprint-core = "0.1.0"
molprint-fp = "0.1.0"
molprint-io = "0.1.0"
libusalign-sys = "0.1.1"

[[bin]]
name = "bench_leiden"
path = "src/bench_leiden.rs"

[[bin]]
name = "bench_fingerprints"
path = "src/bench_fingerprints.rs"

[[bin]]
name = "bench_hnsw"
path = "src/bench_hnsw.rs"
