# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import typing
__all__ = [
    "Cosine",
    "L1",
    "L2",
]

@typing.final
class Cosine:
    r"""
    Cosine distance: ``1 - dot(a, b) / (||a|| * ||b||)``. ``0.0`` if either vector
    is the zero vector.
    
    Example::
    
        import numpy as np
        from relag.kernels.vectors import Cosine
    
        a = np.array([1.0, 0.0], dtype=np.float32)
        b = np.array([0.0, 1.0], dtype=np.float32)
        k = Cosine()
        assert k.call(a, b) == k(a, b) == 1.0
    """
    def __new__(cls) -> Cosine: ...
    def call(self, a: numpy.typing.NDArray[numpy.float32], b: numpy.typing.NDArray[numpy.float32]) -> builtins.float:
        r"""
        Compute the cosine distance between two 1D ``float32`` numpy arrays.
        
        Reads directly from each array's buffer -- no copy.
        
        Args:
            a: First vector.
            b: Second vector.
        
        Returns:
            Distance in ``[0.0, 2.0]``. ``0.0`` means the same direction, ``2.0``
            means exactly opposite directions.
        """
    def __call__(self, a: numpy.typing.NDArray[numpy.float32], b: numpy.typing.NDArray[numpy.float32]) -> builtins.float:
        r"""
        Alias for ``call`` — enables ``kernel(a, b)`` syntax.
        """

@typing.final
class L1:
    r"""
    Manhattan (L1) distance: ``sum(|a_i - b_i|)``.
    
    Example::
    
        import numpy as np
        from relag.kernels.vectors import L1
    
        a = np.array([1.0, 2.0, 3.0], dtype=np.float32)
        b = np.array([4.0, 0.0, 3.0], dtype=np.float32)
        k = L1()
        assert k.call(a, b) == k(a, b) == 5.0
    """
    def __new__(cls) -> L1: ...
    def call(self, a: numpy.typing.NDArray[numpy.float32], b: numpy.typing.NDArray[numpy.float32]) -> builtins.float:
        r"""
        Compute the L1 distance between two 1D ``float32`` numpy arrays.
        
        Reads directly from each array's buffer -- no copy.
        
        Args:
            a: First vector.
            b: Second vector.
        
        Returns:
            Distance in ``[0.0, inf]``. ``0.0`` means identical vectors.
        """
    def __call__(self, a: numpy.typing.NDArray[numpy.float32], b: numpy.typing.NDArray[numpy.float32]) -> builtins.float:
        r"""
        Alias for ``call`` — enables ``kernel(a, b)`` syntax.
        """

@typing.final
class L2:
    r"""
    Euclidean (L2) distance: ``sqrt(sum((a_i - b_i)²))``.
    
    Example::
    
        import numpy as np
        from relag.kernels.vectors import L2
    
        a = np.array([0.0, 0.0], dtype=np.float32)
        b = np.array([3.0, 4.0], dtype=np.float32)
        k = L2()
        assert k.call(a, b) == k(a, b) == 5.0
    """
    def __new__(cls) -> L2: ...
    def call(self, a: numpy.typing.NDArray[numpy.float32], b: numpy.typing.NDArray[numpy.float32]) -> builtins.float:
        r"""
        Compute the L2 distance between two 1D ``float32`` numpy arrays.
        
        Reads directly from each array's buffer -- no copy.
        
        Args:
            a: First vector.
            b: Second vector.
        
        Returns:
            Distance in ``[0.0, inf]``. ``0.0`` means identical vectors.
        """
    def __call__(self, a: numpy.typing.NDArray[numpy.float32], b: numpy.typing.NDArray[numpy.float32]) -> builtins.float:
        r"""
        Alias for ``call`` — enables ``kernel(a, b)`` syntax.
        """

