[package]
name = "py-relag"
version = "0.0.4"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "py_relag"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.28.3"}
pyo3-stub-gen = "0.22.1"
relag-core = { package = "relag", path = "../relag" }
indicatif = "0.17"
rayon = "1"
numpy = "0.28"
anyhow = "1.0.102"
bincode = { version = "<3.0", features = ["derive"] }
