# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
from relag import utils
import typing
__all__ = [
    "NormMode",
    "USAlignKernel",
]

@typing.final
class USAlignKernel:
    r"""
    Protein structure comparison kernel using USalign TM-score.
    
    Operates on pre-loaded ``PdbStructure`` objects (from ``relag.utils``).
    Returns ``1.0 - TM-score`` so that identical structures have distance 0
    and unrelated structures have distance approaching 1.
    
    Example::
    
        from relag.utils import PdbStructure
        from relag.kernels.structures import USAlignKernel, NormMode
    
        s1 = PdbStructure("1abc.pdb")
        s2 = PdbStructure("1xyz.pdb")
        k  = USAlignKernel()                  # default: NormMode.Min
        d  = k(s1, s2)                         # float in [0, 1]
    """
    def __new__(cls, norm_mode: NormMode = NormMode.Min, fast: builtins.bool = True) -> USAlignKernel:
        r"""
        Create a USAlignKernel.
        
        Args:
            norm_mode: Which TM-score normalization to use. Defaults to ``NormMode.Min``.
            fast: Use USalign's fast alignment mode (~3-5x faster, slight accuracy loss).
                Recommended when building HNSW indexes where approximate distances suffice.
        """
    def call(self, a: utils.PdbStructure, b: utils.PdbStructure) -> builtins.float:
        r"""
        Compute the structure distance between two ``PdbStructure`` objects.
        
        Args:
            a: First structure.
            b: Second structure.
        
        Returns:
            Distance in ``[0.0, 1.0]``. ``0.0`` means structurally identical,
            values near ``1.0`` indicate unrelated folds.
        """
    def __call__(self, a: utils.PdbStructure, b: utils.PdbStructure) -> builtins.float:
        r"""
        Alias for ``call`` — enables ``kernel(a, b)`` syntax.
        """

@typing.final
class NormMode(enum.Enum):
    r"""
    TM-score normalization strategy.
    
    USalign returns two scores per alignment:
    
    - ``TM1``: normalized by the length of the first structure (query).
    - ``TM2``: normalized by the length of the second structure (target).
    
    - ``Min`` (default): ``min(TM1, TM2)`` — conservative, symmetric.
    - ``Query``: use ``TM1`` only.
    - ``Target``: use ``TM2`` only.
    """
    Min = ...
    Query = ...
    Target = ...

