# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import typing
from . import alignments
from . import molecules
from . import protspam
from . import structures
from . import vectors
__all__ = [
    "KernelVariant",
    "alignments",
    "molecules",
    "protspam",
    "structures",
    "vectors",
    "zip_kernel",
]

@typing.final
class KernelVariant(enum.Enum):
    AlignmentGlobal = ...
    AlignmentLocal = ...
    TanimotoBit = ...
    TanimotoReal = ...
    Structure = ...
    ProtSpam = ...
    Cosine = ...
    L1 = ...
    L2 = ...

def zip_kernel(variant: KernelVariant, data1: typing.Any, data2: typing.Any, n_threads: builtins.int = 0, progress: builtins.bool = True, *args: typing.Any, **kwargs: typing.Any) -> builtins.list[builtins.float]:
    r"""
    Compute pairwise kernel scores between two equal-length sequences of data items in parallel.
    
    Evaluates ``kernel(data1[i], data2[i])`` for each index ``i`` and returns the scores
    as a flat ``list[float]`` of length ``len(data1)``.
    
    Extra positional and keyword arguments are forwarded to the kernel constructor.
    
    Args:
        variant: Which kernel to use.
        data1: First sequence of items.
        data2: Second sequence of items. Must have the same length as ``data1``.
        n_threads: Number of parallel threads. ``0`` uses all available cores.
        progress: Show a progress bar. Defaults to ``True``.
    
    Returns:
        A ``list[float]`` of length ``len(data1)`` where ``result[i] = kernel(data1[i], data2[i])``.
    
    Raises:
        ValueError: If ``data1`` and ``data2`` have different lengths.
    
    Example::
    
        from relag import KernelVariant
        from relag.kernels import zip_kernel
    
        seqs1 = ["MKTAYIAK", "ACDEFGHIKLM"]
        seqs2 = ["MKTAYIAKQR", "ACDEF"]
        scores = zip_kernel(KernelVariant.AlignmentGlobal, seqs1, seqs2)
        # scores[i] == kernel(seqs1[i], seqs2[i])
    """

