# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
from relag import kernels
import typing
__all__ = [
    "CsrGraph",
    "EdgeStore",
    "EdgeStoreIter",
    "HNSWConfig",
    "HNSWIndex",
    "HNSWState",
    "INWeightType",
    "LeidenObjective",
    "exact_edges",
    "exact_nearest_neighbors",
    "find_communities",
    "find_components",
    "partition",
]

@typing.final
class CsrGraph:
    r"""
    Compressed Sparse Row graph built from an ``EdgeStore``. A CSR graph is compact, and highly
    efficient for traversal, exploiting cache structure and maximizing cache hits. However, it is
    immutable, so adding a new node or edge require building the full graph again.
    
    ``CsrGraph`` is an immutable adjacency structure. Because of its property of being very
    efficient for traversal, it is used by graph algorithms such as ``partition`` and
    ``connected_components``.
    
    Properties:
        - ``n``: Number of nodes.
        - ``m``: Sum of all edge weights (or total edge count when ``inweight_type=INWeightType.Unweighted``).
    
    Example::
    
        from relag.core import EdgeStore, CsrGraph
    
        store = EdgeStore(4, [(0,1,0.9),(1,2,0.8),(2,3,0.6)])
        g = CsrGraph(store)
        print(g.n)               # 4
        print(g.neighbors(1))    # [(0, 0.9), (2, 0.8)]
        print(g.strength(1))     # 1.7
    """
    @property
    def n(self) -> builtins.int:
        r"""
        Number of nodes
        """
    @property
    def m(self) -> builtins.float:
        r"""
        Total weight (each edge counted once)
        """
    def __new__(cls, edges: EdgeStore, inweight_type: INWeightType = INWeightType.Distance) -> CsrGraph:
        r"""
        Build a CsrGraph from an EdgeStore.
        
        Args:
            edges: The edge store to build the graph from.
            inweight_type: How to convert the raw ``EdgeStore`` weights to
                           similarity-like weights. See ``INWeightType``. Pass
                           ``INWeightType.Unweighted`` to ignore weights entirely
                           (every edge gets weight ``1.0``). Defaults to
                           ``INWeightType.Distance``.
        """
    def neighbors(self, v: builtins.int) -> builtins.list[tuple[builtins.int, builtins.float]]:
        r"""
        Return the neighbors of node ``v`` as a list of ``(node_id, weight)`` pairs.
        
        Args:
            v: Zero-based node index.
        """
    def strength(self, v: builtins.int) -> builtins.float:
        r"""
        Return the strength (weighted degree) of node ``v``.
        
        When the graph is unweighted this equals the degree (number of neighbors).
        
        Args:
            v: Zero-based node index.
        """
    def subgraph(self, nodes: typing.Sequence[builtins.int]) -> tuple[CsrGraph, builtins.dict[builtins.int, builtins.int]]:
        r"""
        Extract a subgraph composed of a subset of nodes.
        
        New node ids are assigned contiguously in the order ``nodes`` is given.
        
        All edges pointing outside the subgraph are ignores.
        
        Args:
            nodes: Node ids to keep, in the desired new order.
        
        Returns:
            A tuple ``(subgraph, mapping)`` where ``mapping`` is a dict from old node id
            to new node id.
        
        Example::
        
            sub, mapping = g.subgraph([2, 0, 3])
            print(sub.n)      # 3
            print(mapping)    # {0: 1, 2: 0, 3: 2}
        """

@typing.final
class EdgeStore:
    r"""
    A compact, flat list of weighted directed edges between integer node IDs.
    
    ``EdgeStore`` is the central data carrier in relag: it is produced by
    ``exact_edges`` and ``HNSWState.edges``, consumed by ``CsrGraph``, and can be
    persisted to disk for later reuse.
    
    Each edge is a triple ``(src, dst, weight)`` where ``src`` and ``dst`` are
    zero-based node indices in ``[0, node_count)`` and ``weight`` is a ``float32``
    value.
    
    Example::
    
        from relag.core import EdgeStore
    
        store = EdgeStore(node_count=3, edges=[(0, 1, 0.9), (1, 2, 0.7)])
        print(len(store))     # 2
        print(store[0])       # (0, 1, 0.9)
        for src, dst, w in store:
            print(src, dst, w)
    
        # numpy-style boolean masking: keep only the edges where mask[i] is True
        store[[True, False]]   # EdgeStore with only (0, 1, 0.9)
    """
    def __new__(cls, node_count: builtins.int, edges: typing.Sequence[tuple[builtins.int, builtins.int, builtins.float]]) -> EdgeStore:
        r"""
        Create a new EdgeStore.
        
        Args:
            node_count: Total number of nodes in the graph (must be ≥ the largest node ID + 1).
            edges: List of ``(src, dst, weight)`` triples. Weights are ``float32`` similarity scores.
        """
    def edges(self) -> builtins.list[tuple[builtins.int, builtins.int, builtins.float]]:
        r"""
        Return all edges as a list of ``(src, dst, weight)`` triples.
        """
    def node_count(self) -> builtins.int:
        r"""
        Return the total number of nodes this store was created with.
        """
    def graph(self, inweight_type: INWeightType = INWeightType.Distance) -> CsrGraph:
        r"""
        Build a ``CsrGraph`` from this edge store.
        
        Args:
            inweight_type: How to convert the raw edge weights to similarity-like weights.
                           See ``INWeightType``. Pass ``INWeightType.Unweighted`` to ignore
                           weights entirely (every edge gets weight ``1.0``). Defaults to
                           ``INWeightType.Distance``, meaning weights are assumed to be a distance
                           measurement, and are converted to similarities.
        
        Returns:
            A ``CsrGraph`` backed by this edge list.
        """
    def save(self, path: builtins.str) -> None:
        r"""
        Serialize this EdgeStore to disk. It supports two file formats: ``text`` with
        ``.edgelist`` extension or ``binary`` with ``.edgestr`` extension. Binary is usually 2x
        more space efficient at the cost of not being human-readable.
        
        **Version compatibility (binary format only):** The binary ``.edgestr`` format is versioned
        to the exact package version and is not forward or backward compatible. A file saved with
        a different package version will fail to load with a version mismatch error. The text
        ``.edgelist`` format has no version stamp and may be portable across versions.
        
        Args:
            path: Destination file path.
        
        Raises:
            IOError: On any I/O failure.
        Example::
        
            from relag.core import EdgeStore
        
            store = EdgeStore(node_count=3, edges=[(0, 1, 0.9), (1, 2, 0.7)])
            store.save("my/path/myedges.edgelist") # Text format
            store.save("my/path/myedges.edgestr")  # Bin format
        """
    @staticmethod
    def load(path: builtins.str) -> EdgeStore:
        r"""
        Load an EdgeStore that was previously saved with ``EdgeStore.save``. It infers the format
        from the extension of the path, ``.edgelist`` or ``.edgestr``.
        
        **Version compatibility (binary format only):** The binary ``.edgestr`` format is versioned
        to the exact package version. A file saved with a different package version will fail to
        load with a version mismatch error. There is no forward or backward compatibility. The text
        ``.edgelist`` format is not versioned and may be portable across versions.
        
        Args:
            path: Path to the file produced by ``save``.
        
        Returns:
            The deserialized ``EdgeStore``.
        
        Raises:
            IOError: If the file cannot be read, the format is invalid, or (for ``.edgestr`` files)
                     the saved version does not match the running package version.
        """
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, idx: builtins.int | typing.Sequence[builtins.bool]) -> tuple[builtins.int, builtins.int, builtins.float]  |  EdgeStore:
        r"""
        Index by position (``store[3]``, supports negative indices) or by a boolean
        mask (``store[mask]``, one bool per edge), analogous to numpy's ``arr[mask]``.
        A mask keeps only the edges where ``mask[i]`` is ``True``; ``node_count`` is
        left unchanged.
        """
    def __iter__(self) -> EdgeStoreIter: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class EdgeStoreIter:
    ...

@typing.final
class HNSWConfig:
    r"""
    Configuration for the HNSW approximate nearest-neighbour index.
    
    All parameters have sensible defaults; in most cases you only need to ``ef_construction``, and
    ``proximity_threshold``.
    
    **Parameters:**
    
    - ``proximity_threshold`` *(float)* — Distance threshold under which a connection is established in the proximity graph.
    - ``ef_construction`` *(int)* — Candidate list size during build. Default ``64``.
    - ``m`` *(int)* — Bidirectional links per node at layers > 0.
      Higher = better recall, more memory, slower build. Typical: 8–64.
    - ``m_max`` *(int)* — Maximum connections per node at layers > 0. Usually equal to ``m``.
    - ``m_max0`` *(int)* — Maximum connections at layer 0. Usually ``2 * m``.
    - ``m_l`` *(float)* — Level generation factor. Usually ``0.36 ≈ 1 / ln(m)``.
    - ``ef_init`` *(int)* — Candidate list size during initial-layer insertion. Almost always 1 for
      a greedy search.
    - ``extend_candidates`` *(bool)* — Use neighbors of neighbors as candidates, making search more exhaustive.
    - ``keep_pruned_connections`` *(bool)* — Retain discarded candidates to fill up to ``m`` connections when not enough connections are found.
    - ``keep_all_edges`` *(bool)* — Record every below-threshold distance computed during build into
      the proximity graph returned by ``edges()``. Default ``True``. Setting it to ``False`` makes
      ``edges()`` return ``None``, but removes a per-hit locked hashmap insert from the hot path.
      Worth doing when the proximity graph is not required.
    - ``cache_capacity`` *(int)* — Maximum cached kernel scores. Increasing it increase the memory
      footprint, but also cache hits, which can improve runtime performances for computationally expensive kernels.
      Set to ``0`` to disable the cache entirely — every distance is recomputed directly, which is
      faster for cheap kernels (e.g. ``TanimotoBit``/``TanimotoReal``) where cache overhead exceeds the
      cost of the kernel itself.
    - ``cache_shards`` *(int)* — Number of cache shards (reduces lock contention).
    - ``n_threads`` *(int)* — Threads used during build. ``0`` = all available cores.
    - ``shuffle`` *(bool)* — Shuffle insertion order before building. Can create a less biased
      graph, but reduces cache hits, which increases runtime.
    - ``use_heuristic`` *(bool)* — Use the heuristic neighbour-selection from the paper (recommended).
    - ``strict_ef`` *(bool)* — If ``True``, enforces the result set size to exactly ``ef`` during search. Empirically, setting this to ``False`` can improve runtime performance, as it allows halving ``ef_construction`` without sacrificing accuracy.
    - ``threshold_based_neighbourhood`` *(bool)* — Select a minimum of ``m`` neighbors like the classic algorithm, but doesn't bound the neighbourhood size as all candidates that are closer than the threshold are kept.
    - ``total_size`` *(int | None)* — Expected final dataset size. When set, the graph is pre-allocated
      for this many items instead of the initial data length, so incremental ``extend_build`` calls
      don't re-allocate. Exceeding it is allowed; the graph grows as usual. Default ``None``.
    """
    @property
    def m(self) -> builtins.int: ...
    @property
    def m_max(self) -> builtins.int: ...
    @property
    def m_max0(self) -> builtins.int: ...
    @property
    def m_l(self) -> builtins.float: ...
    @property
    def ef_init(self) -> builtins.int: ...
    @property
    def ef_construction(self) -> builtins.int: ...
    @property
    def extend_candidates(self) -> builtins.bool: ...
    @property
    def keep_pruned_connections(self) -> builtins.bool: ...
    @property
    def keep_all_edges(self) -> builtins.bool: ...
    @property
    def cache_capacity(self) -> builtins.int: ...
    @property
    def cache_shards(self) -> builtins.int: ...
    @property
    def proximity_threshold(self) -> builtins.float: ...
    @property
    def n_threads(self) -> builtins.int: ...
    @property
    def shuffle(self) -> builtins.bool: ...
    @property
    def use_heuristic(self) -> builtins.bool: ...
    @property
    def strict_ef(self) -> builtins.bool: ...
    @property
    def threshold_based_neighbourhood(self) -> builtins.bool: ...
    @property
    def total_size(self) -> typing.Optional[builtins.int]: ...
    def __new__(cls, proximity_threshold: builtins.float = 0.0, ef_construction: builtins.int = 64, m: builtins.int = 16, m_max: builtins.int = 16, m_max0: builtins.int = 32, m_l: builtins.float = 0.36, ef_init: builtins.int = 1, extend_candidates: builtins.bool = False, keep_pruned_connections: builtins.bool = True, keep_all_edges: builtins.bool = True, cache_capacity: builtins.int = 2000000, cache_shards: builtins.int = 64, n_threads: builtins.int = 0, shuffle: builtins.bool = False, use_heuristic: builtins.bool = True, strict_ef: builtins.bool = False, threshold_based_neighbourhood: builtins.bool = False, total_size: typing.Optional[builtins.int] = None) -> HNSWConfig:
        r"""
        Create an HNSWConfig. See class docstring for parameter descriptions.
        """
    def dict(self) -> dict:
        r"""
        Return the configuration as a plain Python dict.
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class HNSWIndex:
    r"""
    Read-only snapshot of the HNSW graph structure after a build.
    
    Obtained via ``HNSWState.index``. Primarily useful for inspection,
    serialisation, and debugging; normal users interact with ``HNSWState``
    instead.
    
    Properties:
        dataset_size (int): Number of items indexed.
        layers (list): Nested multi-layer adjacency list ``layers[layer][node] = [neighbor_ids]``.
        entry_point (tuple | None): ``(layer, node_id)`` of the global entry point, or ``None`` if empty.
        max_layers (int): Number of layers in the hierarchy.
        proximity_edges (list): List of ``((src, dst), score)`` for proximity-threshold edges.
        config (HNSWConfig): The config used to build this index.
    """
    @property
    def dataset_size(self) -> builtins.int: ...
    @property
    def layers(self) -> builtins.list[builtins.list[builtins.list[builtins.int]]]:
        r"""
        Nested multi-layer adjacency list, `layers[layer][node] = [neighbor_ids]`. Layers
        above 0 may be stored sparsely internally (most nodes aren't present at those
        layers); this densifies them into the full node-id-indexed shape on access.
        """
    @property
    def entry_point(self) -> typing.Optional[tuple[builtins.int, builtins.int]]: ...
    @property
    def max_layers(self) -> builtins.int: ...
    @property
    def proximity_edges(self) -> builtins.list[tuple[tuple[builtins.int, builtins.int], builtins.float]]: ...
    @property
    def config(self) -> HNSWConfig: ...
    def save(self, path: builtins.str) -> None:
        r"""
        Save the object to a binary representation (e.g. *.hnsw* file).
        
        The binary format is versioned to the exact package version and is not
        forward or backward compatible. A file saved with version X can only be
        loaded by the exact same version X. Files saved with a different version
        will fail to load with a version mismatch error.
        
        Args:
            path: Destination file path (recommended with a .hnsw extension)
        
        Raises:
            RuntimeError: On serialisation or I/O failure.
        """
    @staticmethod
    def load(path: builtins.str) -> HNSWIndex:
        r"""
        Load an index previously saved with ``HNSWIndex.save``.
        
        **Version compatibility:** The binary format is versioned to the exact package version.
        A file saved with a different package version (older or newer) will fail to load with
        a version mismatch error. There is no forward or backward compatibility guarantee during
        the unstable pre-0.1.0 phase.
        
        Args:
            path: Path to the saved file.
        
        Returns:
            The deserialised ``HNSWIndex``.
        
        Raises:
            RuntimeError: If the file cannot be read, the format is invalid, or the saved
                          version does not match the running package version.
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class HNSWState:
    r"""
    Stateful Hierarchical Navigable Small World (HNSW) approximate nearest-neighbour index. This
    class is used to build and search in the index, whereas ``HNSWIndex`` is a read-only *internal*
    representation of the index used for saving / loading / structure exploration.
    
    ``HNSWState`` wraps the dataset and the graph index together. The typical
    workflow is:
    
    1. Construct with the data and a ``KernelVariant``.
    2. Call ``build()`` to insert all items and form the graph.
    3. Call ``search()`` to query, or ``edges()`` to extract the proximity graph
       for downstream clustering / splitting.
    
    HNSW parameters (``proximity_threshold``, ``ef_construction``, …) are the same as ``HNSWConfig``
    and can be passed directly to the constructor as keyword arguments.
    
    ``data`` may be any Python iterable — a ``list``, a ``tuple``, a generator, anything with
    ``__iter__``. It's drained one item at a time into the constructor's own Rust-owned copy,
    so a generator never needs to be fully materialized into a Python-side list first — both
    copies never need to coexist at once. That matters when a single item's Python
    representation is large enough that two full-dataset copies wouldn't fit in memory
    together. When ``data`` supports ``len()`` (a ``list``/``tuple``), that's used to
    pre-size the Rust-owned copy exactly; it doesn't change how ``data`` is walked.
    
    Args:
        variant: Kernel to use (e.g.  ``KernelVariant.AlignmentGlobal``, ``KernelVariant.AlignmentLocal``, ``KernelVariant.TanimotoBit``, *etc*).
        data: The dataset — a list of items matching the kernel type (e.g. ``list[str]`` or
            ``list[np.ndarray]``), or any other Python iterable of such items (e.g. a generator).
        proximity_threshold, ef_construction, m, m_max, m_max0, m_l, ef_init, extend_candidates,
            keep_pruned_connections, keep_all_edges, cache_capacity, cache_shards,
            n_threads, shuffle, use_heuristic, strict_ef,
            threshold_based_neighbourhood, total_size: See ``HNSWConfig`` for descriptions.
    
    Raises:
        ValueError: If ``data`` is empty.
    
    Properties:
        config (HNSWConfig): The config in use.
        index (HNSWIndex): A snapshot of the current graph structure.
    
    Example::
    
        from relag import HNSWState, KernelVariant
    
        seqs = ["MKTAYIAK", "MKTAYIAKQR", "ACDEFGHIKLM", "MKTAYIAKQRQIS"]
        state = HNSWState(KernelVariant.AlignmentGlobal, seqs, proximity_threshold=0.3, ef_construction=64)
        state.build()
        results = state.search(["MKTAYIAK"], k=2)
        # results[0] -> [(0, 0.0), (1, 0.12)]
    
        store = state.edges()        # EdgeStore for graph-based splitting
        state.save("index.hnsw")
        state2 = HNSWState.load(KernelVariant.AlignmentGlobal, "index.hnsw", seqs)
    """
    @property
    def is_built(self) -> builtins.bool:
        r"""
        Whether ``build`` has been called on this index.
        """
    @property
    def config(self) -> HNSWConfig:
        r"""
        Config used to initiate this object.
        """
    @property
    def index(self) -> HNSWIndex:
        r"""
        HNSWIndex snapshot.
        """
    def __new__(cls, variant: kernels.KernelVariant, data: typing.Any, *args: typing.Any, proximity_threshold: builtins.float = 0.0, ef_construction: builtins.int = 64, m: builtins.int = 16, m_max: builtins.int = 16, m_max0: builtins.int = 32, m_l: builtins.float = 0.36, ef_init: builtins.int = 1, extend_candidates: builtins.bool = False, keep_pruned_connections: builtins.bool = True, keep_all_edges: builtins.bool = True, cache_capacity: builtins.int = 2000000, cache_shards: builtins.int = 64, n_threads: builtins.int = 0, shuffle: builtins.bool = False, use_heuristic: builtins.bool = True, strict_ef: builtins.bool = False, threshold_based_neighbourhood: builtins.bool = False, total_size: typing.Optional[builtins.int] = None, **kwargs: typing.Any) -> HNSWState: ...
    def build(self, progress: builtins.bool = True) -> None:
        r"""
        Build the HNSW index by inserting all data items.
        
        Must be called before ``search`` or ``edges``. Calling ``build`` a second
        time raises a ``RuntimeError``; construct a new ``HNSWState`` instead.
        
        Args:
            progress: Display a progress bar. Defaults to ``True``.
        
        Raises:
            RuntimeError: If the index has already been built.
        """
    def extend_build(self, data: typing.Any, progress: builtins.bool = True) -> None:
        r"""
        Extend an already-built index with more data: appended to the dataset, then
        inserted into the graph. Existing nodes and edges are untouched.
        
        ``data`` accepts any Python iterable, same as the constructor (see ``HNSWState``'s
        class docstring) -- drained one item at a time so a generator never needs to be
        fully materialized into a Python-side list first.
        
        Args:
            data: The new items to add (same type as the original dataset).
            progress: Display a progress bar. Defaults to ``True``.
        
        Raises:
            RuntimeError: If ``build`` has not been called yet.
        
        Example::
        
            from relag import HNSWState, KernelVariant
        
            seqs = ["MKTAYIAK", "MKTAYIAKQR", "ACDEFGHIKLM"]
            state = HNSWState(KernelVariant.AlignmentGlobal, seqs, proximity_threshold=0.3)
            state.build()
        
            more_seqs = ["MKTAYIAKQRQIS", "ACDEFGHIKLMNP"]
            state.extend_build(more_seqs)
            state.index.dataset_size  # 5
        
            results = state.search(["MKTAYIAKQRQIS"], k=2)
            # results[0] -> [(3, 0.0), (1, 0.23)] -- found itself among the new items
        """
    def search(self, queries: typing.Any, k: builtins.int = 1, ef: builtins.int = 64, threads: builtins.int = 0, progress: builtins.bool = True) -> builtins.list[builtins.list[tuple[builtins.int, builtins.float]]]:
        r"""
        Search the index for approximate nearest neighbours.
        
        For each query item, returns the ``k`` nearest items in the dataset,
        sorted by ascending distance. The quality of the approximation is
        controlled by ``ef``: larger values explore more candidates and improve
        recall at the cost of speed.
        
        Args:
            queries: List of query items (same type as the indexed data).
            k: Number of nearest neighbours to return per query. Defaults to ``1``.
            ef: Size of the dynamic candidate list during search. Must be ≥ ``k``.
                Defaults to ``64``.
            threads: Number of parallel threads. ``0`` = all available cores.
            progress: Display a progress bar. Defaults to ``True``.
        
        Returns:
            A list of length ``len(queries)``. Each element is a sorted list of
            up to ``k`` tuples ``(dataset_index, distance)``.
        
        Raises:
            RuntimeError: If ``build`` has not been called yet.
        """
    def edges(self) -> typing.Optional[EdgeStore]:
        r"""
        Extract the proximity graph as an ``EdgeStore``.
        
        Returns all edges found during ``build``. All distance measurements below the
        ``proximity_threshold``.
        
        Returns:
            An ``EdgeStore`` with ``node_count = dataset_size``, or ``None`` if the index was built
            with ``keep_all_edges=False``.
        """
    def get_layer(self, layer_idx: builtins.int = 0, directed: builtins.bool = False, weights: builtins.bool = True, progress: builtins.bool = True) -> EdgeStore:
        r"""
        Return the adjacency lists for a specific HNSW layer.
        
        Args:
            layer_idx: Zero-based layer index (0 = base layer with most nodes).
        
        Returns:
            A list of length ``dataset_size`` where element ``i`` is the list of
            neighbour IDs of node ``i`` at this layer. Node IDs are their index in the original dataset.
        
        Raises:
            IndexError: If ``layer_idx`` is out of range.
        Edges of one HNSW layer, as an ``EdgeStore``.
        
        Args:
            layer_idx: Zero-based layer index (0 = base layer with most nodes).
            directed: If ``True``, every edge is returned exactly as internally
                recorded -- an undirected connection contributes one entry per
                endpoint, i.e. ``(x, y)`` is distinct from ``(y, x)``. If
                ``False`` (default), edges are canonicalized and deduplicated,
                so each undirected pair appears exactly once.
            weights: If ``True`` (default), each edge's weight is its real
                distance, computed on the fly since not stored in the hierarchical graph.
                If ``False``, every edge gets weight
                ``1.0`` -- much cheaper when the real distance isn't needed.
            progress: Display a progress bar while distances are computed.
                Only meaningful when ``weights=True``. Defaults to ``False``.
        
        Returns:
            An ``EdgeStore`` with ``node_count = dataset_size``.
        
        Raises:
            IndexError: If ``layer_idx`` is out of range.
        """
    def save(self, path: builtins.str) -> None:
        r"""
        Serialize the full state (index + config) to a binary file.
        
        The saved file can be loaded back with ``HNSWState.load``. The original
        data must be provided again at load time (it is not embedded in the file).
        
        **Version compatibility:** The binary format is versioned to the exact package version.
        A file saved with a different package version (older or newer) will fail to load with
        a version mismatch error. There is no forward or backward compatibility guarantee during
        the unstable pre-0.1.0 phase.
        
        Args:
            path: Destination file path.
        
        Raises:
            RuntimeError: On serialisation or I/O failure.
        """
    @staticmethod
    def load(variant: kernels.KernelVariant, path: builtins.str, data: typing.Any, *args: typing.Any, **kwargs: typing.Any) -> HNSWState:
        r"""
        Load an HNSWState form a binary file saved with ``HNSWState.save``.
        
        **Version compatibility:** The binary format is versioned to the exact package version.
        A file saved with a different package version (older or newer) will fail to load with
        a version mismatch error. There is no forward or backward compatibility guarantee during
        the unstable pre-0.1.0 phase.
        
        ``data`` accepts any Python iterable, same as the constructor (see ``HNSWState``'s
        class docstring) — including a generator re-reading a cache file.
        
        Args:
            variant: Must match the kernel used during the original build.
            path: Path to the saved file.
            data: The original dataset (required to re-attach the kernel).
        
        Returns:
            The restored ``HNSWState``, ready to call ``search`` or ``edges`` if the index was built.
        
        Raises:
            RuntimeError: If the file cannot be read, the format is invalid, or the saved
                          version does not match the running package version.
        """

@typing.final
class INWeightType(enum.Enum):
    r"""
    How to convert a raw ``EdgeStore`` weight into the similarity-like edge weight
    used internally by ``CsrGraph`` and the Leiden algorithm.
    
    - ``Similarity`` — the raw weight is already a similarity; used as-is.
    - ``Distance`` — the raw weight is a distance in ``[0, ∞)``; mapped to
      ``1 / (1 + w)`` so closer nodes get a higher weight.
    - ``SimilarityComplement`` — the raw weight is ``1 - similarity``; mapped
      back to a similarity via ``1 - w``.
    - ``Unweighted`` — the raw weight is ignored; every edge weight is set to ``1.0``.
    """
    Similarity = ...
    Distance = ...
    SimilarityComplement = ...
    Unweighted = ...

@typing.final
class LeidenObjective(enum.Enum):
    r"""
    Objective function used by the Leiden community-detection algorithm.
    
    - ``Modularity`` — Maximise Newman-Girvan modularity. Good default for most graphs.
    - ``CPM`` — Constant Potts Model. Finds communities of a fixed internal density.
    """
    Modularity = ...
    CPM = ...

def exact_edges(variant: kernels.KernelVariant, data: typing.Any, proximity_threshold: builtins.float = 0.5, n_threads: builtins.int = 0, progress: builtins.bool = True, *args: typing.Any, **kwargs: typing.Any) -> EdgeStore:
    r"""
    Compute all pairs of data points whose distance is below a threshold (exact, brute-force).
    
    Evaluates every unordered pair ``(i, j)`` with ``i < j`` and records an edge
    when ``kernel(data[i], data[j]) <= proximity_threshold``. This is O(n²) in the number
    of data points; prefer the approximate``HNSWState`` for large datasets.
    
    Extra positional and keyword arguments are forwarded to the kernel constructor.
    
    Args:
        variant: Which kernel to use (``KernelVariant.AlignmentGlobal`` or
                 ``KernelVariant.AlignmentLocal``).
        data: Sequence of data items (e.g. ``list[str]`` for protein sequences).
        proximity_threshold: Maximum distance for an edge to be recorded.
        n_threads: Number of parallel threads. ``0`` uses all available cores.
        progress: Show a progress bar. Defaults to ``True``.
    
    Returns:
        An ``EdgeStore`` containing all edges whose distance ≤ ``proximity_threshold``.
    
    Example::
    
        from relag import KernelVariant, exact_edges
    
        seqs = ["MKTAYIAK", "MKTAYIAKQR", "ACDEFGHIKLM"]
        store = exact_edges(KernelVariant.AlignmentGlobal, seqs, proximity_threshold=0.5)
        print(len(store))   # number of similar pairs
    """

def exact_nearest_neighbors(variant: kernels.KernelVariant, queries: typing.Any, references: typing.Any, k: builtins.int, threads: builtins.int = 0, progress: builtins.bool = True, *args: typing.Any, **kwargs: typing.Any) -> builtins.list[builtins.list[tuple[builtins.int, builtins.float]]]:
    r"""
    Find the k nearest neighbors of each query in a reference set (exact, brute-force).
    
    For every query item, scores it against every reference item using the
    chosen kernel and returns the top-k references sorted by ascending
    distance. Complexity is O(n_queries × n_references); prefer
    ``HNSWState.search`` for approximate nearest neighbors with large datasets.
    
    Extra positional and keyword arguments are forwarded to the kernel constructor.
    
    Args:
        variant: Which kernel to use (``KernelVariant.AlignmentGlobal`` or
                 ``KernelVariant.AlignmentsLocal``).
        queries: Sequence of query items.
        references: Sequence of reference items to search over. List of items of the same type of the selected kernel variant.
        k: Number of nearest neighbors to return per query. List of items of the same type of the selected kernel variant.
        threads: Number of parallel threads. ``0`` uses all available cores.
        progress: Show a progress bar. Defaults to ``True``.
    
    Returns:
        A list of length ``len(queries)``. Each element is a list of up to ``k``
        tuples ``(reference_index, distance)`` sorted by ascending distance.
    
    Example::
    
        from relag import KernelVariant, exact_nearest_neighbors
    
        queries = ["MKTAYIAK"]
        refs    = ["MKTAYIAKQR", "ACDEFGHIKLM", "MKTAYIAKQRQ"]
        results = exact_nearest_neighbors(
            KernelVariant.AlignmentGlobal, queries, refs, k=2
        )
        # results[0] -> [(0, 0.20), (2, 0.27)]
    """

def find_communities(graph: CsrGraph, gamma: builtins.float = 1.0, beta: builtins.float = 0.01, n_iterations: builtins.int = 2, objective: LeidenObjective = LeidenObjective.Modularity) -> builtins.list[builtins.int]:
    r"""
    Detect communities in a graph with the Leiden algorithm.
    
    The Leiden algorithm is an improvement over Louvain that guarantees
    well-connected communities. Use the returned cluster labels with
    ``partition`` to produce train/test splits that consider community boundaries.
    
    Args:
        graph: The graph to partition into communities.
        gamma: Resolution parameter. Higher values produce more, smaller communities.
               For ``Modularity``, typical range is 0.5–2.0; default ``1.0``.
               For ``CPM``, it represents the minimum internal edge density.
        beta: Randomness parameter controlling the refinement phase.
              Smaller values yield more deterministic results. Default ``0.01``.
        n_iterations: Number of optimisation passes. More iterations improve
                      quality at the cost of runtime.
        objective: ``LeidenObjective.Modularity`` (default) or ``LeidenObjective.CPM``.
    
    Returns:
        A list of length ``graph.n`` where element ``i`` is the cluster ID of node ``i``.
        Cluster IDs are arbitrary non-negative integers.
    
    Example::
    
        from relag.core import CsrGraph, EdgeStore, find_communities, LeidenObjective, INWeightType
    
        store = EdgeStore(4, [(0,1,0.9),(1,2,0.8),(2,3,0.6)])
        g = CsrGraph(store, inweight_type=INWeightType.Similarity)
        clusters = find_communities(g, gamma=1.0, n_iterations=20) # e.g. [0, 1, 2, 3]
    """

def find_components(graph: CsrGraph) -> builtins.list[builtins.int]:
    r"""
    Finds the connected components of a graph.
    
    Runs a standard BFS/union-find over the graph and assigns each node to
    its component.
    
    Args:
        graph: The graph to find components.
    
    Returns:
        A list of length ``graph.n`` where element ``i`` is the component ID of
        node ``i``. IDs are arbitrary non-negative integers.
    
    Example::
    
        from relag.core import EdgeStore, find_components
    
        store = EdgeStore(6, [(0,1,0.9),(1,2,0.8),(3,4,0.7),(4,5,0.6)])
        g = store.graph()
        clusters = find_components(g) # [0, 0, 0, 1, 1, 1]
    """

def partition(clusters: typing.Sequence[builtins.int], graph: CsrGraph, test_ratio: builtins.float = 0.2, seed: typing.Optional[builtins.int] = None, post_filtering: builtins.bool = False) -> tuple[builtins.list[builtins.int], builtins.list[builtins.int]]:
    r"""
    Split a clustered dataset into train and test index sets along clusters
    
    Clusters are kept intact — no cluster is split across train and test.
    The function greedily and randomly assigns whole clusters to the test set until the test size
    is larger than ``test_ratio``, then assigns the rest to train.
    
    This is the key function for leakage-free dataset splitting: run
    ``find_communities``, ``find_components``, or your own clustering, then call ``partition``
    to obtain indices you can use to slice your data arrays.
    
    Args:
        clusters: A list of cluster IDs, one per data point (as returned by
                  ``find_communities`` or ``connected_components``). Length must
                  equal the number of nodes in ``graph``.
        graph: The graph used to derive community structure. Its node count
               must match ``len(clusters)``.
        test_ratio: Target fraction of data points to place in the test set.
                    The actual fraction may differ slightly because clusters
                    are indivisible. Defaults to ``0.2``.
        seed: Optional integer seed for reproducible cluster shuffling.
              Pass ``None`` for a random assignment.
        post_filtering: If ``True``, remove train nodes that share an edge with
                        any test node (stricter leakage prevention at the
                        cost of a smaller train set). Use only when clusters are found from
                        communities (``find_communities``). It won't have any effect when used with
                        ``connected_components`` as this prevents inter-cluster connections.
    
    Returns:
        A tuple ``(train_indices, test_indices)`` of zero-based data-point indices.
    
    Raises:
        ValueError: If ``clusters`` length does not match ``graph.n``, or if
                    ``test_ratio`` is not in ``(0, 1)``.
    
    Example::
    
        from relag.core import (
            EdgeStore, CsrGraph, find_communities, partition, INWeightType
        )
    
        store = EdgeStore(6, [(0,1,0.9),(1,2,0.8),(3,4,0.7),(4,5,0.6)])
        g = CsrGraph(store, inweight_type=INWeightType.Similarity)
        clusters = find_communities(g) # or connected_components(g)
        train_idx, test_idx = partition(clusters, g, test_ratio=0.3, seed=42)
    """

