[project]
name = "pytests"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "relag",
    "pytest>=9.0.3",
    "rdkit>=2026.3.1",
    "igraph>=1.0.0",
    "pandas>=3.0.3",
    "pyarrow>=24.0.0",
]

[tool.uv.sources]
relag = { path = "../py" }

[dependency-groups]
dev = [
    "scipy>=1.17.1",
    "maturin>=1.13.3",
    "matplotlib>=3.10.9",
    "seaborn>=0.13.2",
    "requests>=2.34.2",
]
