# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
from relag import utils
import typing
__all__ = [
    "ProtSpamDistance",
    "ProtSpamKernel",
]

@typing.final
class ProtSpamKernel:
    r"""
    Distance between two ``SWSequence``, ProtSpaM-style: for each pattern in a
    shared ``SWPatternSet``, match spaced words by key (grouping ties into "blocks"),
    score the best-aligned spaced word pair within each matching block against
    BLOSUM62, and pool mismatches at don't-care positions into a mismatch rate.
    Reports either that raw rate or a Kimura-corrected evolutionary distance, per
    ``distance``.
    
    Every ``SWSequence`` passed to ``call`` must have been built from the same
    ``SWPatternSet`` as this kernel's ``patterns()`` (or an equal copy of it).
    
    Example::
    
        from relag.kernels.protspam import ProtSpamKernel, ProtSpamDistance
        from relag.utils import SWPatternSet, SWSequence
    
        sequences = [
            "MKTAYIAKQRQISFVKSHFSRQLEERLGLIEVQAPILSRVGDGTQDNLSGAEK",
            "MKTAYIAKQRQISFVKSHFSRQLEERLGLIEVQAPILSRVGDGTQDNLSGAEA",
        ]
    
        # A RasBhari-optimized pattern set, shared by every SWSequence and the kernel.
        patterns = SWPatternSet(5, 6, 20)
    
        swseqs = [SWSequence(s, patterns) for s in sequences]
    
        kernel = ProtSpamKernel(patterns, distance=ProtSpamDistance.Evolutionary)
        distance = kernel.call(swseqs[0], swseqs[1])
        distance = kernel(swseqs[0], swseqs[1])  # equivalent -- kernel(a, b) syntax
        assert distance >= 0.0
    """
    def __new__(cls, patterns: utils.SWPatternSet, significance_threshold: builtins.int = 0, distance: ProtSpamDistance = ProtSpamDistance.Evolutionary) -> ProtSpamKernel:
        r"""
        Build a kernel over ``patterns`` -- also the pattern set every ``SWSequence``
        passed to ``call`` must have been built from.
        
        Args:
            patterns: The shared pattern set.
            significance_threshold: Minimum BLOSUM62 score (over don't-care
                positions) for a spaced-word match to be considered homologous.
                ProtSpaM's own default is ``0``.
            distance: Which value ``call`` reports. Default ``ProtSpamDistance.Evolutionary``.
        """
    def call(self, ref_sample: utils.SWSequence, query: utils.SWSequence) -> builtins.float:
        r"""
        Compute the distance between ``ref_sample`` and ``query``, per this kernel's
        ``distance()`` mode.
        
        Args:
            ref_sample: Reference sequence. Must have been built from the same
                ``SWPatternSet`` as this kernel's ``patterns()``.
            query: Query sequence. Same requirement.
        
        Returns:
            The distance -- see ``ProtSpamDistance``.
        
        Panics:
            ``ref_sample``/``query`` must have been built from the same
            ``SWPatternSet`` as this kernel's ``patterns()``. If they weren't, this
            can panic (index out of range, if the mismatched set has fewer patterns)
            or -- more insidiously -- silently compare the wrong patterns' spaced
            words against each other with no panic at all, if the mismatched set
            merely has a different pattern at the same index.
        """
    def __call__(self, ref_sample: utils.SWSequence, query: utils.SWSequence) -> builtins.float:
        r"""
        Alias for ``call`` -- enables ``kernel(a, b)`` syntax.
        """
    def patterns(self) -> utils.SWPatternSet:
        r"""
        The shared pattern set spaced words are matched against.
        """
    def significance_threshold(self) -> builtins.int:
        r"""
        Minimum BLOSUM62 score for a spaced-word match to be considered homologous.
        """
    def distance(self) -> ProtSpamDistance:
        r"""
        Which value ``call`` reports.
        """

@typing.final
class ProtSpamDistance(enum.Enum):
    r"""
    Which distance ``ProtSpamKernel.call`` reports.
    
    - ``MismatchRate``: the raw mismatch rate itself (fraction of don't-care
      positions that mismatch, pooled across every pattern's accepted spaced-word
      matches) -- always in ``[0, 1]``. ``1.0`` if no spaced word matched at all, or
      if every accepted match's don't-care positions mismatched outright.
    - ``Evolutionary``: the mismatch rate corrected into a distance via the Kimura
      two-parameter formula -- in ``[0, inf]``. ``inf`` if the mismatch rate is
      undefined (no match at all) or high enough (``> ~0.8541``) that the
      correction's log argument is non-positive.
    """
    MismatchRate = ...
    Evolutionary = ...

